name: rezid
description: A top-up game.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.1.0
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mlbb.png
    - assets/images/ff.png
    - assets/images/pubgm.png