// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSPAvUNeDufcP8NBSOnPYk-7mU-mab4aY',
    appId: '1:619069499302:web:90ab40f1adc98573af1167',
    messagingSenderId: '619069499302',
    projectId: 'rezappid',
    authDomain: 'rezappid.firebaseapp.com',
    storageBucket: 'rezappid.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP86X_BBeT3NdKgynJ03OBhzQvdsjG4QY',
    appId: '1:619069499302:android:75e7f85e388509bcaf1167',
    messagingSenderId: '619069499302',
    projectId: 'rezappid',
    storageBucket: 'rezappid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUHhe2bZIgA8WIXeKlseF_6fgqdOvTjNM',
    appId: '1:619069499302:ios:40cae0176a6edcc6af1167',
    messagingSenderId: '619069499302',
    projectId: 'rezappid',
    storageBucket: 'rezappid.firebasestorage.app',
    iosBundleId: 'com.example.rezid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUHhe2bZIgA8WIXeKlseF_6fgqdOvTjNM',
    appId: '1:619069499302:ios:40cae0176a6edcc6af1167',
    messagingSenderId: '619069499302',
    projectId: 'rezappid',
    storageBucket: 'rezappid.firebasestorage.app',
    iosBundleId: 'com.example.rezid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSPAvUNeDufcP8NBSOnPYk-7mU-mab4aY',
    appId: '1:619069499302:web:d2580fd9ea19caecaf1167',
    messagingSenderId: '619069499302',
    projectId: 'rezappid',
    authDomain: 'rezappid.firebaseapp.com',
    storageBucket: 'rezappid.firebasestorage.app',
  );
}
